services:
  express:
    build:
      context: backend
    container_name: backend
    environment:
      - PORT=3000
      - DATABASE_URL="mongodb+srv://andrewviquang:lq6sAzk9hVue5wlq@labcluster.jxghisa.mongodb.net/boilerplate?retryWrites=true&w=majority&appName=LabCluster"
    networks:
      - node-network
    volumes:
      - ./backend:/usr/src/app
    tty: true
    ports:
      - '3000:3000'

  react:
    build:
      context: frontend
    container_name: frontend
    networks:
      - node-network
    volumes:
      - ./frontend:/usr/src/app
    tty: true
    ports:
      - '8080:8080'

  nginx:
    build:
      context: nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - '8000:80'
    networks:
      - node-network
    depends_on:
      - express
      - react

networks:
  node-network:
    driver: bridge
